name: Kodi Addon-Check (Matrix)

on: [push, pull_request]

jobs:
  kodi-addon-checker-matrix:
          runs-on: ubuntu-latest
          name: Kodi addon checker
          steps:
          - name: Checkout
            uses: actions/checkout@v1
          - name: Modify addon.xml for matrix
            run: |
              python3 tools/modify_addonxml_matrix.py
          - name: Kodi addon checker validation (matrix)
            id: kodi-addon-checker-matrix
            uses: xbmc/action-kodi-addon-checker@v1.0
            with:
              kodi-version: matrix
